#+OPTIONS: html-postamble:nil toc:nil html-style:nil
#+EXPORT_FILE_NAME: new-tab.html
#+TITLE: New tab
#+HTML_HEAD: <link rel="stylesheet" href="extension.css"/>

#+ATTR_HTML: :id introduction
#+BEGIN_snippet
This simple new tab page is provided by the Emacs keybindings extension to make custom keybindings work here. If you prefer the default tab page press C-h ? to open the extension settings, and uncheck "Use custom 'new tab' page to allow overriding keybindings". You can also customise this page there - almost all page elements can be hidden.
#+END_snippet

#+ATTR_HTML: :id github
#+BEGIN_snippet
If you have any problems please check the [[https://github.com/bwachter/emacs-keybinding/issues][issues on github]], and file a new one if none exists. Help is also very welcome - especially for making this look prettier, which only requires HTML/CSS skills.
#+END_snippet

#+ATTR_HTML: :id input_label
#+BEGIN_snippet
Enter URL or search term:
#+END_snippet

#+BEGIN_EXPORT html
<form autocomplete="off" id="form">
<div style="position:relative;display:inline-block;width:100%">
<label><input type="search" name="urlbar" id="urlbar" style="width:100%" autofocus/><br/>
</div>
</form>

<script src="keybindings.js"></script>
<script src="theme.js"></script>
<script src="new-tab.js"></script>
#+END_EXPORT

#+ATTR_HTML: :id url_instructions
#+BEGIN_snippet
Entered values will be processed as follows:

1. if the entered string is a valid URL (including protocol specifier), open it.
2. try if the entered string will become a valid URL for a HTTP GET request by prepending https:// and http://, in that order.
3. try to search for the string entered with the default search engine.
#+END_snippet

#+ATTR_HTML: :id search_engines
#+BEGIN_snippet
The following search engines are configured:

#+ATTR_HTML: :id search_engine_table
| alias | search engine name | default |
|-------+--------------------+---------|
|       |                    |         |
#+END_snippet

#+ATTR_HTML: :id top_sites
#+BEGIN_snippet
#+BEGIN_EXPORT html
<h2>Frequently visited sites</h2>
<div class="icon-group" id="top-site-group"></div>
#+END_EXPORT
#+END_snippet
