#!/usr/bin/emacs --script
;;
;; extension build script
;;
;; with emacs in non-standard path, do emacs --script package.el
;;
;; this can take `firefox' or `chrome' as argument to build for the specific
;; browser only, otherwise it'll generate both archives.
;;
;; manifest.json is now generated by this, and no longer in git - so for local
;; development, this must be run at least once.
;;
;; any changes to org-mode files need a rebuild of the html files, ideally also
;; through this script.

(require 'org)
(require 'vc-git)
(require 'json)

;; this is the baseline manifest, set to invalid manifest version to be sure
;; it gets rebuilt later on.
(setq base-manifest
      '((version_name . "0.2.6")
        (manifest_version . 1)
        (name . "Emacs-keybinding")
        (description . "An addon for using Firefox with Emacs keybinding")
        (version . "0.2.6")
        (homepage_url . "https://github.com/bwachter/emacs-keybinding")
        (author . "Wang Kai")
        (browser_specific_settings .
                                   ((gecko . ((id . "{e95dd474-674a-4768-9965-8360529685a5}")))))
        (permissions . ["activeTab" "history" "search" "storage" "tabs" "topSites"])
        (browser_action .
                        ((default_icon . (("19" . "icons/emacs-19.png")
                                          ("38" . "icons/emacs-38.png")))))
        (icons . (("48" . "icons/emacs-48.png")
                  ("96" . "icons/emacs-96.png")))
        (options_ui . ((page . "options.html")))
        (content_scripts .
                         [((matches . ["<all_urls>"])
                           (js . ["keybindings.js"])) ])))

(defun get-git-info ()
  "Get Git metadata using Emacs built-in VC-Git.

Returns a list with information:
  :last-tag is the last tag found
  :head-is-tagged returns t if HEAD has a tag, nil otherwise
  :head-tag returns the tag on HEAD, nil otherwise
  :count returns the commit count since last tag
  :hash returns the hash of HEAD"
  (let* ((last-tag (with-temp-buffer
                     (vc-git-command t nil nil "describe" "--tags" "--abbrev=0")
                     (goto-char (point-min))
                     (if (re-search-forward "[^\n]+" nil t) (match-string 0) "none")))
         (head-tag (with-temp-buffer
                     (vc-git-command t nil nil "tag" "--points-at" "HEAD")
                     (goto-char (point-min))
                     (if (re-search-forward "[^\n]+" nil t) (match-string 0) nil)))
         (count    (with-temp-buffer
                     (vc-git-command t nil nil "rev-list" "--count" (concat last-tag "..HEAD"))
                     (goto-char (point-min))
                     (if (re-search-forward "[0-9]+" nil t) (match-string 0) "0")))
         (rev-hash (with-temp-buffer
                     (vc-git-command t nil nil "rev-parse" "HEAD")
                     (goto-char (point-min))
                     (if (re-search-forward "[^\n]+" nil t) (match-string 0) "unknown"))))
    (list :last-tag last-tag
          :head-is-tagged (if head-tag t nil)
          :head-tag head-tag
          :count count
          :hash rev-hash)))

(defun create-manifest (git-info manifest-path is-chrome)
  "Build browser specific manifest.json

This marks developer version, and can handle differences for chrome and
firefox - so eventually we might be able to build both archives from a single
run.

This also handles different manifest versions."
  (let* ((tag      (plist-get git-info :last-tag))
         (on-tag   (plist-get git-info :head-tag))
         (count    (plist-get git-info :count))
         (hash     (plist-get git-info :hash))
         (manifest base-manifest))

    (if is-chrome
        ;; chrome: set version and version_name
        (let ((version-name (build-version-name git-info)))
          (setf (alist-get 'manifest_version manifest) 3)
          (setf (alist-get 'version manifest) tag)
          (setf (alist-get 'version_name manifest) version-name)
          ;; developer key doesn't seem to exist for chrome
          (setf manifest (assq-delete-all 'developer manifest)))
      ;; firefox: remove version name, add 4th digit for developer builds
      (let ((version-number (if (or on-tag (string= count "0"))
                                tag
                              (format "%s.%s" tag count))))
        (setf (alist-get 'manifest_version manifest) 2)
        (setf (alist-get 'version manifest) version-number)
        ;; add 'find' permissions
        (setf (alist-get 'permissions manifest)
              (vconcat (alist-get 'permissions manifest) ["find"]))
        ;; add the developer key
        (setf (alist-get 'developer manifest) '(("name" . "Bernd Wachter")))
        ;; remove version_name if it exists
        (setf manifest (assq-delete-all 'version_name manifest))))

    ;; now the generic, non browser specific v2/v3 handling
    (let ((manifest-version (alist-get 'manifest_version manifest)))
      (cond
       ((eq manifest-version 2)
        (message "Building for manifest V2")
        (setf (alist-get 'background manifest) '(("scripts" . ("background.js")))))
       ((eq manifest-version 3)
        (message "Building for manifest V3")
        (setf manifest (assq-delete-all 'browser_action manifest))
        (setf manifest (assq-delete-all 'background manifest)))
       (t
        (error "Unsupported manifest version: %s" manifest-version))))

    (with-temp-file manifest-path
      (let ((json-encoding-pretty-print t))
        (insert (json-encode manifest))))
    (message "Updated %s for %s" manifest-path (if is-chrome "Chrome" "Firefox"))))

(defun build-version-name (git-info)
  "Build the version name from the git info string"
  (let* ((tag      (plist-get git-info :last-tag))
         (on-tag   (plist-get git-info :head-tag))
         (count    (plist-get git-info :count))
         (hash     (plist-get git-info :hash)))
    (if on-tag tag (format "%s-dev.%s.%s" tag count hash))))

(defun make-html()
  "Export all org files to html. This expects files to have #+EXPORT_FILE_NAME: set correctly."
  (let ((org-files (directory-files-recursively "." (rx ".org"))))
    (mapcar (lambda (file)
              (let ((default-directory (file-name-directory (expand-file-name file))))
                (with-temp-buffer
                  (insert-file-contents (file-name-nondirectory file))
                  (org-mode)
                  (org-html-export-to-html)))) org-files)))

(defun make-zip(is-chrome)
  "Pack up everything that should be part of the extension in a zip file. Zip
output will be available in the *zip* buffer. Also updates manifest.json with
version info from git tags."
  (let* ((git-info (get-git-info))
         (zip-name (format "Emacs-keybinding-%s-%s.zip"
                           (build-version-name git-info)
                           (if is-chrome "chrome" "firefox")))
         (zip-files))
    (if git-info
        (create-manifest git-info "manifest.json" is-chrome)
      (error "This needs to run in a git checkout"))
    (setq zip-files (directory-files-recursively "." (rx (or ".html" ".js" ".json" ".png" "icons" "LICENSE"))))
    (apply #'call-process "zip" nil "*zip*" nil "-r" "-FS" zip-name (append zip-files))))

(message "Building html pages...")
(make-html)

(let ((target (car argv)))
  (cond
   ((string= target "firefox")
    (message "Building for Firefox only...")
    (make-zip nil))

   ((string= target "chrome")
    (message "Building for Chrome only...")
    (make-zip t))

   (t
    (message "No specific target or unknown target '%s'; building both..." (or target "all"))
    (make-zip nil)
    (make-zip t))))
